apps/proyectos/urls.py
from django.urls import path

from .views import (ImportarProyectosJIRA,
                    RegistrarProyecto,
                    ListadoProyecto,
                    ModificarProyecto,
                    RegistrarProyectoEmpleado,
                    ListadoProyectosEmpleados,
                    ModificarProyectoEmpleado)


app_name = 'proyectos'

urlpatterns = [
    
    path('importar-proyectos-jira/', ImportarProyectosJIRA.as_view(), name='importar_proyectos_jira'),

    path('registrar-proyecto/', RegistrarProyecto.as_view(), name='registrar_proyecto'),
    path('modificar-proyecto/<int:pk>', ModificarProyecto.as_view(), name='modificar_proyecto'),
    path('listado-proyectos/', ListadoProyecto.as_view(), name='listado_proyectos'),

    path('registrar-proyecto-empleado/', RegistrarProyectoEmpleado.as_view(), name='registrar_proyecto_empleado'),
    path('modificar-proyecto-empleado/<int:pk>', ModificarProyectoEmpleado.as_view(), name='modificar_proyecto_empleado'),    
    path('listado-proyectos-empleado/', ListadoProyectosEmpleados.as_view(), name='listado_proyecto_empleados'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from apps.usuarios.views import PaginaInicio

urlpatterns = [
    path('', PaginaInicio.as_view(), name='inicio'),
    path('admin/', admin.site.urls),
    path("select2/", include("django_select2.urls")),
    path('core/', include('apps.core.urls', namespace='core')),
    path('usuarios/', include('apps.usuarios.urls', namespace='usuarios')),
    path('actividades/', include('apps.actividades.urls', namespace='actividades')),
    path('proyectos/', include('apps.proyectos.urls', namespace='proyectos')),
    path('estimaciones/', include('apps.estimaciones.urls', namespace='estimaciones')),
    path('dashboard/', include('apps.dashboard.urls', namespace='dashboards')),
]

apps/proyectos/models/contactos_proyecto.py
# Django
from django.db import models
from django.core.validators import RegexValidator

# Utilities
from apps.utils.models import EstimacionModel
from ..models import Proyecto


class ContactoProyecto(EstimacionModel):
    proyecto = models.ForeignKey(
        Proyecto,
        related_name='contactos_empresa_proyecto',
        verbose_name="Proyecto*",
        on_delete=models.PROTECT
    )
    nombres = models.CharField(max_length=75, verbose_name="Nombres del contacto*")
    apellidos = models.CharField(max_length=75, verbose_name="Apellidos del contacto*")
    correo_electronico = models.EmailField('Correo electrónico*')
    phone_regex = RegexValidator(
        regex=r'\+?1?\d{7,10}$',
        message="El numero de teléfono debe tener entre 7 y 10 digitos:"
    )
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True, verbose_name='Teléfono celular')
    cargo = models.CharField(max_length=100, verbose_name="Cargo del contacto en la empresa a la que pertenece", default='')

    def __str__(self):
        """Return username."""
        return self.username

    @classmethod
    def buscar_por_id(cls, id_elemento:int) -> 'Usuario':
        try:
            return cls.objects.get(pk=id_elemento)
        except cls.DoesNotExist:
            return cls.objects.none()


    @classmethod
    def existe_por_id(cls, id_elemento:int) -> bool:
        return cls.objects.filter(pk=id_elemento).exists()


    @classmethod
    def buscar_por_correo_electronico(cls, correo_electronico:str) -> 'Usuario':
        try:
            return cls.objects.get(correo_electronico=correo_electronico)
        except cls.DoesNotExist:
            return cls.objects.none()

apps/proyectos/models/proyectos.py
from django.db import models

from apps.utils.models import EstimacionModel

from apps.usuarios.models.empresas import Empresa
from apps.usuarios.models.empleados import Empleado

class Proyecto(EstimacionModel):
    empresa = models.ForeignKey(
        Empresa,
        related_name='proyectos_empresa', 
        verbose_name="Empresas asociadas al proyecto",
        on_delete=models.SET_NULL,
        null=True
    )
    empleados = models.ManyToManyField(
        Empleado,
        through='ProyectoEmpleado',
        related_name="proyecto_empleado",
        blank=True,
        verbose_name="Empleados asociados al proyecto"
    )
    identificador_jira = models.CharField(max_length=80, unique=True, verbose_name="Identificador del proyecto JIRA*")
    nombre = models.CharField(max_length=80, unique=True, verbose_name="Nombre del proyecto*")
    descripcion = models.TextField(verbose_name='Descripción', null=True, blank=True)
    fecha_inicio = models.DateTimeField(
        'Iniciado a',
        help_text='Fecha y hora en la que se inicio el proyecto',
        blank=True, null=True
    )
    fecha_finalizacion = models.DateTimeField(
        'Finalizado a',
        help_text='Fecha y hora de finalización del proyecto',
        blank=True, null=True
    )

    def __str__(self):
        """Return username."""
        return self.nombre

    
    @staticmethod
    def existe_por_identificador_jira(identificador:str) -> bool:
        return Proyecto.objects.filter(identificador_jira=identificador).exists()

    @staticmethod
    def buscar_por_identificador_jira(identificador:str) -> bool:
        try:
            return Proyecto.objects.get(identificador_jira=identificador)
        except Proyecto.DoesNotExist:
            return Proyecto.objects.none()

    @staticmethod
    def buscar_por_nombre(nombre:str) -> 'Proyecto':
        try:
            return Proyecto.objects.get(nombre=nombre)
        except Proyecto.DoesNotExist:
            return None

apps/proyectos/models/proyectos_empleados.py
from django.db import models

from apps.utils.models import EstimacionModel

from apps.usuarios.models.empleados import Empleado
from ..models.proyectos import Proyecto

class ProyectoEmpleado(EstimacionModel):
    empleado = models.ForeignKey(
        Empleado,
        related_name='proyectos_empleado_empleado',
        verbose_name="Empleado*",
        on_delete=models.PROTECT
    )
    proyecto = models.ForeignKey(
        Proyecto,
        related_name='proyectos_empleado_proyecto',
        verbose_name="Proyecto*",
        on_delete=models.PROTECT
    )
    fecha_inicio = models.DateTimeField(
        'Iniciado a',
        auto_now_add=True,
        help_text='Fecha y hora en la que se inicio el proyecto'
    )
    fecha_finalizacion = models.DateTimeField(
        'Finalizado a',
        auto_now=True,
        help_text='Fecha y hora de finalización del proyecto'
    )

    def __str__(self) -> str:
        return "{}-{}".format(self.proyecto, self.empleado)

    @staticmethod
    def crear_y_obtener(empleado:'Empleado', proyecto:'Proyecto') -> 'TipoActividad':

        if ProyectoEmpleado.existe(empleado, proyecto):
            return ProyectoEmpleado.buscar_por_empleado_y_proyecto(empleado, proyecto)
        else:
            ProyectoEmpleado.objects.create(empleado=empleado, proyecto=proyecto)
       

    @staticmethod
    def existe(empleado:'Empleado', proyecto:'Proyecto') -> bool:
        try:
            ProyectoEmpleado.objects.get(empleado=empleado, proyecto=proyecto)
            return True
        except ProyectoEmpleado.DoesNotExist:
            return False

    @staticmethod
    def buscar_por_empleado_y_proyecto(empleado:'Empleado', proyecto:'Proyecto') -> "ProyectoEmpleado":
        try:
            return ProyectoEmpleado.objects.get(empleado=empleado, proyecto=proyecto)
        except ProyectoEmpleado.DoesNotExist:
            return None

apps/proyectos/forms/contactos_proyecto.py
from django import forms
from django.forms import modelformset_factory

from ..models.contactos_proyecto import ContactoProyecto

class RegistrarContactoForm(forms.ModelForm):
    class Meta:
        model = ContactoProyecto
        fields = ("nombres", "apellidos", "correo_electronico", "phone_number", "cargo")

ContactoFormSet = modelformset_factory(ContactoProyecto, form=RegistrarContactoForm, extra=1)

apps/proyectos/forms/proyectos.py
from django import forms

from ..models.proyectos import Proyecto


class RegistrarProyectoForm(forms.ModelForm):
    
    fecha_inicio = forms.DateTimeField(
                input_formats=['%Y-%m-%d'],
                widget=forms.TextInput(
                        attrs={
                            'class':'datepicker',
                            'placeholder': 'Fecha inicio',
                        }
                    ),
                label="", required=False)
    fecha_finalizacion = forms.DateTimeField(
                input_formats=['%Y-%m-%d'],
                widget=forms.TextInput(
                        attrs={
                            'class':'datepicker',
                            'placeholder': 'Fecha fin'
                        }
                    ),
                label="", required=False)
    class Meta:
        model = Proyecto
        fields = ("empresa", "nombre", "identificador_jira", "descripcion", "fecha_inicio", "fecha_finalizacion", "esta_activo")
        widgets = {
            'descripcion': forms.Textarea(
                attrs={
                    'rows': 7,
                    'cols': 22,
                    'style':'resize:none;'
                }
            )
        }

apps/proyectos/forms/proyectos_empleados.py
from django import forms

from ..models.proyectos_empleados import ProyectoEmpleado

class RegistrarProyectoEmpleadoForm(forms.ModelForm):
    
    class Meta:
        model = ProyectoEmpleado
        fields = ("empleado", "proyecto", "esta_activo")

apps/proyectos/views/proyectos.py
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView
from django.views.generic.base import TemplateView

from ..models.proyectos import Proyecto
from ..models.contactos_proyecto import ContactoProyecto
from ..forms import (RegistrarProyectoForm,
                     ContactoFormSet)

from apps.utils.mixin import MensajeMixin
from apps.utils.clases.jira.ConexionJira import Jira

from braces.views import LoginRequiredMixin

class RegistrarProyecto(LoginRequiredMixin, MensajeMixin, CreateView):
    model = Proyecto
    form_class = RegistrarProyectoForm
    success_url = reverse_lazy("proyectos:listado_proyectos")
    template_name = "proyectos/proyectos/registrar.html"
    mensaje_exito = "Proyecto registrado correctamente"
    mensaje_error = "Error al registrar el proyecto, por favor verificar los datos"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.formset_estructuras = ContactoFormSet(queryset=ContactoProyecto.objects.none(), prefix="contacto")

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['formset'] = self.formset_estructuras
        return data

    def post(self, *args, **kwargs):

        formset = ContactoFormSet(self.request.POST, prefix="contacto")

        if formset.is_valid():
            self.form_valid(self.get_form())
            return self.formset_valid(formset)
        else:
            errores = ''
            for form in formset:
                for _, errors in form.errors.items():
                    errores += ('{}'.format(','.join(errors)))

            messages.error(self.request, "{}, {}".format(self.mensaje_error,errores))
            return redirect('proyectos:registrar_proyecto')

    def formset_valid(self, formset):

        for form in formset:
            contacto = form.save(commit=False)
            contacto.proyecto = self.object
            contacto.esta_activo = True
            contacto.save()
            
        return self.form_valid(self.get_form())


class ModificarProyecto(LoginRequiredMixin, MensajeMixin, UpdateView):
    model = Proyecto
    form_class = RegistrarProyectoForm
    template_name = "proyectos/proyectos/modificar.html"
    success_url = reverse_lazy("proyectos:listado_proyectos")
    mensaje_exito = "Proyecto modificado correctamente"
    mensaje_error = "Error al modificar el proyecto, por favor verificar los datos"


class ListadoProyecto(LoginRequiredMixin, ListView):
    model = Proyecto
    context_object_name = "proyectos"
    template_name = "proyectos/proyectos/listado.html"



class ImportarProyectosJIRA(LoginRequiredMixin, TemplateView):
    success_url = reverse_lazy("proyectos:listado_proyectos")
    template_name = "proyectos/proyectos/importar_jira.html"

    def dispatch(self, request, *args, **kwargs):
        self.jira = Jira()
        return super().dispatch(request, *args, **kwargs)


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['proyectos'] = self.jira.consultar_todos_los_proyectos()

        proyectos_registrados = list(Proyecto.obtener_todos().values_list('identificador_jira', flat=True))
        listado_proyectos_no_registrados = list()
        for proyecto in context['proyectos']:
            if not proyecto['key'] in proyectos_registrados:
                listado_proyectos_no_registrados.append(proyecto)
        
        context['proyectos'] = listado_proyectos_no_registrados
        if self.request.GET:
            for proyecto in context['proyectos']:
                if Proyecto.existe_por_identificador_jira(proyecto['key']) == False:
                    Proyecto.objects.create(
                        identificador_jira=proyecto['key'],
                        nombre=proyecto['nombre'],
                    )
        return context

apps/proyectos/views/proyectos_empleados.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView

from ..models.proyectos_empleados import ProyectoEmpleado
from ..forms import RegistrarProyectoEmpleadoForm

from apps.utils.mixin import MensajeMixin

from braces.views import LoginRequiredMixin

class RegistrarProyectoEmpleado(LoginRequiredMixin, MensajeMixin, CreateView):
    model = ProyectoEmpleado
    form_class = RegistrarProyectoEmpleadoForm
    success_url = reverse_lazy("proyectos:listado_proyecto_empleados")
    template_name = "proyectos/proyectos_empleados/registrar.html"
    mensaje_exito = "El proyecto ha sido asignado al empleado correctamente"
    mensaje_error = "Error al asignar empleado al proyecto, por favor verificar los datos"


class ModificarProyectoEmpleado(LoginRequiredMixin, MensajeMixin, UpdateView):
    model = ProyectoEmpleado
    form_class = RegistrarProyectoEmpleadoForm
    template_name = "proyectos/proyectos_empleados/modificar.html"
    success_url = reverse_lazy("proyectos:listado_proyecto_empleados")
    mensaje_exito = "Se ha realizado la modificación correctamente"
    mensaje_error = "Error al realizar la modificación, por favor verificar los datos"


class ListadoProyectosEmpleados(LoginRequiredMixin, ListView):
    model = ProyectoEmpleado
    context_object_name = "proyectos_empleados"
    template_name = "proyectos/proyectos_empleados/listado.html"

apps/templates/proyectos/proyectos_empleados/listado.html
{% extends "base_tablas.html" %}

{% load extra_tags %}
{% load bootstrap4 %}
{% load static %}

{% block titulo %}
    Listado de proyectos con trabajador asignado
{% endblock titulo %}

{% block titulo_pagina %}
    Listado de proyectos con trabajador asignado
{% endblock titulo_pagina %}

{% block miga_pan %}
    <li class="breadcrumb-item"><a href="javascript:">Proyectos con trabajador asignado</a></li>
    <li class="breadcrumb-item active">Listado</li>
{% endblock miga_pan %}

{% block titulo_panel %}
    Listado de proyectos con trabajador asignado
{% endblock titulo_panel %}

{% block contenido_panel %}
    <div class="row">
        <div class="col-12">
            <table class="table table-bordered table-hover datatable">
                <thead>
                    <tr>
                        <th>Trabajador</th>
                        <th>Proyecto</th>
                        <th>Estado</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for proyecto in proyectos_empleados %}
                        <tr>
                            <td>{{proyecto.empleado}}</td>
                            <td>{{proyecto.proyecto}}</td>
                            <td>
                                {% include 'componentes/estado/estado-texto.html' with  estado=proyecto.esta_activo%}
                            </td>
                            <td class="text-center">
                                {% url 'proyectos:modificar_proyecto_empleado' proyecto.pk as op_1 %}
                                
                                {% convertir_elementos_a_lista op_1 'Modificar' as lista %}
                                {% include 'componentes/menu_opciones/menu_opciones.html' with  opciones=lista %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock contenido_panel %}

apps/templates/proyectos/proyectos_empleados/modificar.html
{% extends "base.html" %}

{% load bootstrap4 %}
{% load static %}

{% block titulo %}
    Formulario de asignación de proyecto y programador
{% endblock titulo %}

{% block titulo_pagina %}
    Formulario de asignación de proyecto y programador
{% endblock titulo_pagina %}

{% block miga_pan %}
    <li class="breadcrumb-item"><a href="javascipt:">Proyectos con programador</a></li>
    <li class="breadcrumb-item active">Modificar</li>
    <li class="breadcrumb-item active">{{form.instance}}</li>
{% endblock miga_pan %}

{% block titulo_panel %}
    Formulario de asignación de proyecto y programador
{% endblock titulo_panel %}

{% block contenido_panel %}
    <form class="bloquear-ui-enviar" method="post" enctype="multipart/form-data">{% csrf_token %}
        <div class="row">
            <div class="col-12">
                <h4 class="titulo">Información básica de asignación de proyecto y programador</h4>
            </div>
        </div>
        <div>
            {% bootstrap_form form %}
        </div>
        <div class="mt-3">
            {% url 'proyectos:listado_proyecto_empleados' as url_volver%}
            <hr>
            {% include 'componentes/botones/footer_botones.html' with  texto_volver="Volver" texto_accion="Modificar" url_volver=url_volver boton_volver=True boton_accion=True%}
        </div>
    </form>
{% endblock contenido_panel %}

apps/templates/proyectos/proyectos_empleados/registrar.html
{% extends "base.html" %}

{% load bootstrap4 %}
{% load static %}

{% block titulo %}
    Formulario de asignación de proyecto y programador
{% endblock titulo %}

{% block titulo_pagina %}
    Formulario de asignación de proyecto y programador
{% endblock titulo_pagina %}

{% block miga_pan %}
    <li class="breadcrumb-item"><a href="javascipt:">Proyectos con programador</a></li>
    <li class="breadcrumb-item active">Registrar</li>
{% endblock miga_pan %}

{% block titulo_panel %}
    Formulario de asignación de proyecto y programador
{% endblock titulo_panel %}

{% block contenido_panel %}
    <form class="bloquear-ui-enviar" method="post" enctype="multipart/form-data">{% csrf_token %}
        <div class="row">
            <div class="col-12">
                <h4 class="titulo">Información básica de asignación de proyecto y programador</h4>
            </div>
        </div>
        <div>
            {% bootstrap_form form %}
        </div>
        <div class="mt-3">
            {% url 'proyectos:listado_proyecto_empleados' as url_volver%}
            <hr>
            {% include 'componentes/botones/footer_botones.html' with  texto_volver="Volver" texto_accion="Registrar" url_volver=url_volver boton_volver=True boton_accion=True%}
        </div>
    </form>
{% endblock contenido_panel %}