apps/usuarios/urls.py
from django.urls import path

from .views import (ListadoEmpleados,
                    ModificarEmpleado,
                    RegistrarEmpresa,
                    ModificarEmpresa,
                    ListadoEmpresas,
                    RegistrarTrabajador,
                    AsignarCargoTrabajador,
                    ModificarTrabajador,
                    ListadoTrabajadores,
                    ListadoAdministradores,
                    AsignarCargoAdministrador,
                    RegistrarAdministrador,
                    ModificarAdministrador,
                    RegistrarCargo,
                    ListadoCargos,
                    ModificarCargo,
                    InicioSesion,
                    CerrarSesion,
                    ImportarEmpleadosJIRA)
                    

app_name = 'usuarios'

urlpatterns = [

    path('iniciar-sesion/', view=InicioSesion.as_view(), name='iniciar_sesion'),
    path('cerrar-sesion/', view=CerrarSesion.as_view(), name='cerrar_sesion'),

    path('modificar-empleado/<int:pk>', ModificarEmpleado.as_view(), name='modificar_empleado'),
    path('listado-empleado/', ListadoEmpleados.as_view(), name='listado_empleados'),

    path('registrar-empresa/', RegistrarEmpresa.as_view(), name='registrar_empresa'),
    path('modificar-empresa/<int:pk>', ModificarEmpresa.as_view(), name='modificar_empresa'),
    path('listado-empresas/', ListadoEmpresas.as_view(), name='listado_empresas'),

    path('registrar-trabajador/', RegistrarTrabajador.as_view(), name='registrar_trabajador'),
    path('asignar-cargo-trabajador/<int:pk>', AsignarCargoTrabajador.as_view(), name='asignar_cargo_trabajador'),
    path('modificar-trabajador/<int:pk>', ModificarTrabajador.as_view(), name='modificar_trabajador'),
    path('listado-trabajador/', ListadoTrabajadores.as_view(), name='listado_trabajadores'),

    path('registrar-administradores/', RegistrarAdministrador.as_view(), name='registrar_administrador'),
    path('asignar-cargo-administrador/<int:pk>', AsignarCargoAdministrador.as_view(), name='asignar_cargo_administrador'),
    path('modificar-administradores/<int:pk>', ModificarAdministrador.as_view(), name='modificar_administrador'),
    path('listado-administradores/', ListadoAdministradores.as_view(), name='listado_administradores'),

    path('registrar-cargo/', RegistrarCargo.as_view(), name='registrar_cargo'),
    path('listado-cargos/', ListadoCargos.as_view(), name='listado_cargos'),
    path('modificar-cargo/<int:pk>', ModificarCargo.as_view(), name='modificar_cargo'),

    path('importar-empleados/', ImportarEmpleadosJIRA.as_view(), name='importar_empleados'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from apps.usuarios.views import PaginaInicio

urlpatterns = [
    path('', PaginaInicio.as_view(), name='inicio'),
    path('admin/', admin.site.urls),
    path("select2/", include("django_select2.urls")),
    path('core/', include('apps.core.urls', namespace='core')),
    path('usuarios/', include('apps.usuarios.urls', namespace='usuarios')),
    path('actividades/', include('apps.actividades.urls', namespace='actividades')),
    path('proyectos/', include('apps.proyectos.urls', namespace='proyectos')),
    path('estimaciones/', include('apps.estimaciones.urls', namespace='estimaciones')),
    path('dashboard/', include('apps.dashboard.urls', namespace='dashboards')),
]

apps/usuarios/models/administradores.py
from apps.usuarios.models.empleados import Empleado
from apps.usuarios.models.tipos_usuarios import TipoUsuario

class Administrador(Empleado):
    pass

    def save(self, *args, **kwargs):
        self.tipo_usuario = TipoUsuario.obtener_tipo_administrador()
        return super().save(*args, **kwargs)

apps/usuarios/models/clientes.py
from .usuarios import Usuario

class Cliente(Usuario):

    @staticmethod
    def buscar_por_username(username:str) -> 'Cliente':
        try:
            return Cliente.objects.get(username=username)
        except Cliente.DoesNotExist:
            return None
    
    def save(self):
        self.tipo = Usuario.CLIENTE
        return super().save()

apps/usuarios/models/empleados.py
from apps.usuarios.models.tipos_cargo_empelado import CargoEmpleado
from django.db import models

from apps.usuarios.models.tipos_cargos import TipoCargo
from apps.usuarios.models.usuarios import Usuario

class Empleado(Usuario):
    identificador_jira = models.CharField(max_length=80, verbose_name="Identificador único de JIRA", default='', null=True)
    cargos = models.ManyToManyField(
        TipoCargo,
        through='CargoEmpleado',
        related_name="empleados_cargos",
        blank=True,
        verbose_name="Cargos asociados al empleado"
    )

    @classmethod
    def obtener_identificadores(cls) -> 'list<str>':
        return list(cls.objects.values_list('identificador_jira', flat=True))
    
    @staticmethod
    def obtener_empleados_sin_tipo() -> 'Queryset<Empleado>':
        return Empleado.objects.filter(tipo_usuario__isnull=True)

    def obtener_cargos(self):
        return self.empleados_cargos

    def obtener_ultimo_cargo(self):
        cargo = self.cargos.order_by('-cargos_empleado_proyecto__fecha_cambio_cargo').first()
        if cargo:
            return cargo
        return None

    def obtener_cargos_por_orden_ascendente(self):
        return self.cargos.order_by('-cargos_empleado_proyecto__fecha_cambio_cargo').values(
            'nombre',
            'cargos_empleado_proyecto__fecha_cambio_cargo',
            'cargos_empleado_proyecto__fecha_asignado'
            )

apps/usuarios/models/empresas.py
from apps.usuarios.models.usuarios import Usuario
from apps.usuarios.models.tipos_usuarios import TipoUsuario

class Empresa(Usuario):
    pass


    def save(self, *args, **kwargs):
        self.tipo_usuario = TipoUsuario.obtener_tipo_empresa()
        return super().save(*args, **kwargs)

apps/usuarios/models/programadores.py
from django.db import models

from apps.usuarios.models.usuarios import Usuario
from apps.usuarios.models.tipos_usuarios import TipoUsuario
class Programador(Usuario):
    pass

    def save(self, *args, **kwargs):
        self.tipo_usuario = TipoUsuario.buscar_por_identificador(1)
        return super().save(*args, **kwargs)

apps/usuarios/models/tipos_cargo_empelado.py
from django.db import models
from django.utils import timezone

from apps.utils.models import EstimacionModel


class CargoEmpleado(EstimacionModel):
    empleado = models.ForeignKey(
        'Empleado',
        related_name='cargos_empleado_empleado',
        verbose_name="Empleado*",
        on_delete=models.PROTECT
    )
    cargo = models.ForeignKey(
        'TipoCargo',
        related_name='cargos_empleado_proyecto',
        verbose_name="Cargo en la empresa*",
        on_delete=models.PROTECT
    )
    fecha_asignado = models.DateTimeField(
        'Asignado a',
        auto_now_add=True,
        help_text='Fecha y hora en la que se asigno el cargo al trabajador'
    )
    fecha_cambio_cargo = models.DateTimeField(
        'Cambio de cargo a',
        auto_now=True,
        help_text='Fecha y hora en la que se realizo un cambio de cargo al trabajador'
    )

    def save(self, *args, **kwargs):
        self.fecha_cambio_cargo = timezone.now()
        return super().save(*args, **kwargs)

    @staticmethod
    def crear_y_obtener(empleado:'Empleado', cargo:'TipoCargo') -> 'TipoActividad':

        if CargoEmpleado.existe(empleado, cargo):
            return CargoEmpleado.buscar_por_empleado_y_cargo(empleado, cargo)
        else:
            CargoEmpleado.objects.create(empleado=empleado, cargo=cargo)

    @staticmethod
    def existe(empleado:'Empleado', cargo:'TipoCargo') -> bool:
        try:
            CargoEmpleado.objects.get(empleado=empleado, cargo=cargo)
            return True
        except CargoEmpleado.DoesNotExist:
            return False

    @staticmethod
    def buscar_por_empleado_y_cargo(empleado:'Empleado', cargo:'TipoCargo') -> "CargoEmpleado":
        try:
            return CargoEmpleado.objects.get(empleado=empleado, cargo=cargo)
        except CargoEmpleado.DoesNotExist:
            return CargoEmpleado.objects.none()

    @staticmethod
    def buscar_por_empleado(empleado:'Empleado') -> "Queryset<CargoEmpleado>":
        return CargoEmpleado.objects.filter(empleado=empleado)

apps/usuarios/models/tipos_cargos.py
from django.db import models

from apps.utils.models import TiposModel

class TipoCargo(TiposModel):
    descripcion = models.TextField(verbose_name='Descripción', null=True, blank=True)

apps/usuarios/models/tipos_documentos.py
from django.db import models

from apps.utils.models import TiposModel

class TipoDocumento(TiposModel):
    pass

    @staticmethod
    def obtener_tipo_ninguno():
        return TipoDocumento.buscar_por_identificador(1)

    @staticmethod
    def obtener_tipo_nit():
        return TipoDocumento.buscar_por_identificador(2)

    @staticmethod
    def obtener_tipo_cedula():
        return TipoDocumento.buscar_por_identificador(3)

apps/usuarios/models/tipos_usuarios.py
from django.db import models

from apps.utils.models import TiposModel

class TipoUsuario(TiposModel):
    pass

    @staticmethod
    def obtener_tipo_trabajador():
        return TipoUsuario.buscar_por_identificador(1)

    @staticmethod
    def obtener_tipo_empresa():
        return TipoUsuario.buscar_por_identificador(2)

    @staticmethod
    def obtener_tipo_administrador():
        return TipoUsuario.buscar_por_identificador(3)

apps/usuarios/models/trabajadores.py
from django.db import models

from apps.usuarios.models.empleados import Empleado
from apps.usuarios.models.tipos_usuarios import TipoUsuario

class Trabajador(Empleado):
    pass

    def save(self, *args, **kwargs):
        self.tipo_usuario = TipoUsuario.obtener_tipo_trabajador()
        return super().save(*args, **kwargs)

apps/usuarios/forms.py
from django import forms

from apps.usuarios.models.clientes import Cliente

class RegistrarClienteForm(forms.ModelForm):
    
    class Meta:
        model = Cliente
        fields = ("email", "phone_number", "is_verified")

apps/usuarios/forms/administradores.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from apps.usuarios.models.administradores import Administrador
from apps.usuarios.models.tipos_cargos import TipoCargo

class RegistrarAdministradorForm(UserCreationForm):

    cargos = forms.ModelChoiceField(queryset=TipoCargo.obtener_activos())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tipo_documento'].empty_label = None
        self.fields['cargos'].empty_label = None

    class Meta:
        model = Administrador
        fields = ("tipo_documento", "numero_documento", "first_name", "last_name", "email", "phone_number", "cargos")


class ModificarAdministradorForm(UserChangeForm):

    class Meta:
        model = Administrador
        fields = ("tipo_documento", "numero_documento", "first_name", "last_name", "email", "phone_number", "esta_activo")


class AsignarCargoForm(UserChangeForm):

    cargos = forms.ModelChoiceField(label="Cargo actual", queryset=TipoCargo.obtener_activos())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['cargos'].empty_label = None

    class Meta:
        model = Administrador
        fields = ("cargos", )

apps/usuarios/forms/clientes.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from apps.usuarios.models.clientes import Cliente

class RegistrarClienteForm(UserCreationForm):
    
    class Meta:
        model = Cliente
        fields = ("first_name", "last_name", "email", "phone_number")

apps/usuarios/forms/empleados.py
from django import forms
from django.forms import models

from ..models.empleados import Empleado

class ModificarEmpleadoForm(forms.ModelForm):

    class Meta:
        model = Empleado
        fields = ("tipo_usuario", "tipo_documento", "numero_documento", "first_name", "last_name", "email", "phone_number", "esta_activo")

apps/usuarios/forms/empresas.py
from django import forms

from apps.usuarios.models.empresas import Empresa

class RegistrarEmpresaForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tipo_documento'].empty_label = None
        self.fields['first_name'].label = 'Nombre*'
        self.fields['tipo_documento'].label = 'Tipo de documento*'
        self.fields['numero_documento'].label = 'Número del documento*'


    class Meta:
        model = Empresa
        fields = ("tipo_documento", "numero_documento", "first_name", "email", "phone_number", "esta_activo")

apps/usuarios/forms/programadores.py
from django import forms

from apps.usuarios.models.programadores import Programador

class RegistrarProgramadorForm(forms.ModelForm):
    
    class Meta:
        model = Programador
        fields = ("email", "phone_number", "is_verified")

apps/usuarios/forms/tipos_cargos.py
from django import forms

from apps.usuarios.models.tipos_cargos import TipoCargo

class RegistrarCargoForm(forms.ModelForm):

    class Meta:
        model = TipoCargo
        fields = ("nombre", "descripcion")
        widgets = {
            'descripcion': forms.Textarea(
                attrs={
                    'rows': 4,
                    'cols': 22,
                    'style':'resize:none;'
                }
            )
        }

apps/usuarios/forms/trabajadores.py
from django import forms

from apps.usuarios.models.trabajadores import Trabajador
from apps.usuarios.models.tipos_cargos import TipoCargo

class RegistrarTrabajadorForm(forms.ModelForm):

    cargos = forms.ModelChoiceField(queryset=TipoCargo.obtener_activos())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tipo_documento'].empty_label = None
        self.fields['cargos'].empty_label = None

    class Meta:
        model = Trabajador
        fields = ("tipo_documento", "numero_documento", "first_name", "last_name", "email", "phone_number", "cargos")


class ModificarTrabajadorForm(forms.ModelForm):

    class Meta:
        model = Trabajador
        fields = ("tipo_documento", "numero_documento", "first_name", "last_name", "email", "phone_number", "esta_activo")

class AsignarCargoForm(forms.ModelForm):

    cargos = forms.ModelChoiceField(label="Cargo actual", queryset=TipoCargo.obtener_activos())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['cargos'].empty_label = None

    class Meta:
        model = Trabajador
        fields = ("cargos", )

apps/usuarios/forms/usuarios.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

from apps.usuarios.models import Usuario


class FormularioInicioSesion(AuthenticationForm):

    username = forms.CharField(error_messages={
        'required': 'Este campo es requerido',
        'invalid': 'Introduzca un correo valido'
    })
    error_messages = {
        'invalid_login': (
            "Por favor introduzca un %(username)s valido y contraseña."
            "Los campos son sensibles a mayúsculas y minúsculas."
        ),
        'inactive': ("Esta cuenta esta inactiva"),
    }
    #password = forms.PasswordInput(label="Contraseña")

    def _init_(self, *args, **kwargs):
        super()._init_(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Correo electrónico'
        self.fields['password'].widget.attrs['placeholder'] = 'Contraseña'
        self.fields['username'].label = ''
        self.fields['password'].label = ''

    class Meta:
        model = Usuario
        fields = ('username', 'password')

apps/templates/usuarios/trabajadores/asignar_cargo.html
{% extends "base.html" %}

{% load bootstrap4 %}
{% load static %}

{% block titulo %}
    Formulario de asignación e cargo a trabajador
{% endblock titulo %}

{% block titulo_pagina %}
    Formulario de asignación e cargo a trabajador
{% endblock titulo_pagina %}

{% block miga_pan %}
    <li class="breadcrumb-item"><a href="javascipt:">Usuarios</a></li>
    <li class="breadcrumb-item"><a href="javascipt:">Trabajadores</a></li>
    <li class="breadcrumb-item">Asignar</li>
    <li class="breadcrumb-item active">{{form.instance}}</li>
{% endblock miga_pan %}

{% block titulo_panel %}
    Formulario de asignación e cargo a trabajador
{% endblock titulo_panel %}

{% block contenido_panel %}
    <form class="bloquear-ui-enviar" autocomplete="off" method="post" enctype="multipart/form-data">{% csrf_token %}
        <div class="row" >
            <div class="col-xl-12 col-md-6">
                {% bootstrap_field form.cargos %}
            </div>
            <div class="col-xl-12 mt-3">
                {% url 'usuarios:listado_trabajadores' as url_volver%}
                {% include 'componentes/botones/footer_botones.html' with texto_volver="Volver" texto_accion="Asignar cargo" url_volver=url_volver boton_volver=True boton_accion=True%}
            </div>
        </div>
        <hr>
        <div class="row mt-2">
            <div class="col-12">
                <h3 class="text-center">Histórico de cargos</h3>
            </div>
            <table class="table table-bordered table-hover datatable">
                <thead>
                    <tr>
                        <th>Nombres</th>
                        <th>Fecha asignado</th>
                        <th>Fecha cambio cargo</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cargo in form.instance.obtener_cargos_por_orden_ascendente %}
                        <tr>
                            <td>{{cargo.nombre}}</td>
                            <td>{{cargo.cargos_empleado_proyecto__fecha_asignado}}</td>
                            <td>{{cargo.cargos_empleado_proyecto__fecha_cambio_cargo}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </form>
{% endblock contenido_panel %}

apps/templates/usuarios/trabajadores/listado.html
{% extends "base_tablas.html" %}

{% load extra_tags %}

{% block titulo %}
    Listado de trabajadores
{% endblock titulo %}

{% block titulo_pagina %}
    Listado de trabajadores
{% endblock titulo_pagina %}

{% block miga_pan %}
    <li class="breadcrumb-item"><a href="javascript:">Usuarios</a></li>
    <li class="breadcrumb-item"><a href="">Trabajadores</a></li>
    <li class="breadcrumb-item active">Listado</li>
{% endblock miga_pan %}

{% block titulo_panel %}
    Listado de trabajadores
{% endblock titulo_panel %}

{% block contenido_panel %}
    <div class="row">
        <div class="col-12">
            <table class="table table-bordered table-hover datatable">
                <thead>
                    <tr>
                        <th>Nombres</th>
                        <th>Apellidos</th>
                        <th>Email</th>
                        <th>Teléfono</th>
                        <th>Cargo actual</th>
                        <th>Estado</th>
                        <th>Fecha creación</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for trabajador in trabajadores %}
                        <tr>
                            <td>{{trabajador.first_name}}</td>
                            <td>{{trabajador.last_name}}</td>
                            <td>{{trabajador.email}}</td>
                            <td>{{trabajador.phone_number}}</td>
                            <td>{{trabajador.obtener_ultimo_cargo.nombre|default:'-'}}</td>
                            <td>
                                {% include 'componentes/estado/estado-texto.html' with  estado=trabajador.esta_activo%}
                            </td>
                            <td>{{trabajador.creado}}</td>
                            <td class="text-center">
                                {% url 'usuarios:modificar_trabajador' trabajador.pk as op_1 %}
                                {% url 'usuarios:asignar_cargo_trabajador' trabajador.pk as op_2 %}
                                
                                {% convertir_elementos_a_lista op_1 'Modificar' op_2 'Asignar cargo' as lista %}
                                {% include 'componentes/menu_opciones/menu_opciones.html' with  opciones=lista %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock contenido_panel %}

apps/templates/usuarios/trabajadores/modificar.html
{% extends "base.html" %}

{% load bootstrap4 %}
{% load static %}

{% block titulo %}
    Formulario de modificación del trabajador
{% endblock titulo %}

{% block titulo_pagina %}
    Formulario de modificación del trabajador
{% endblock titulo_pagina %}

{% block miga_pan %}
    <li class="breadcrumb-item"><a href="javascipt:">Usuarios</a></li>
    <li class="breadcrumb-item"><a href="javascipt:">Trabajadores</a></li>
    <li class="breadcrumb-item">Modificar</li>
    <li class="breadcrumb-item active">{{form.instance}}</li>

{% endblock miga_pan %}

{% block titulo_panel %}
    Formulario de modificación del trabajador
{% endblock titulo_panel %}

{% block contenido_panel %}
    <form class="bloquear-ui-enviar" method="post" enctype="multipart/form-data">{% csrf_token %}
        <div class="row">
            <div class="col-12">
                <h4 class="titulo">Información básica del programador</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-6">
                {% bootstrap_field form.tipo_documento %}
            </div>
            <div class="col-xl-6">
                {% bootstrap_field form.numero_documento %}
            </div>
            <div class="col-xl-6">
                {% bootstrap_field form.first_name %}
            </div>
            <div class="col-xl-6">
                {% bootstrap_field form.last_name %}
            </div>
            <div class="col-xl-6">
                {% bootstrap_field form.email %}
            </div>
            <div class="col-xl-6">
                {% bootstrap_field form.phone_number %}
            </div>
            <div class="col-xl-12">
                {% bootstrap_field form.esta_activo %}
            </div>
        </div>
        <div class="mt-3">
            {% url 'usuarios:listado_trabajadores' as url_volver%}
            <hr>
            {% include 'componentes/botones/footer_botones.html' with  texto_volver="Volver" texto_accion="Modificar" url_volver=url_volver boton_volver=True boton_accion=True%}
        </div>
       
    </form>
{% endblock contenido_panel %}

apps/templates/usuarios/trabajadores/registrar.html
{% extends "base.html" %}

{% load bootstrap4 %}
{% load static %}

{% block titulo %}
    Formulario de creación del trabajador
{% endblock titulo %}

{% block titulo_pagina %}
    Formulario de creación del trabajador
{% endblock titulo_pagina %}

{% block miga_pan %}
    <li class="breadcrumb-item"><a href="javascipt:">Usuarios</a></li>
    <li class="breadcrumb-item"><a href="javascipt:">Trabajadores</a></li>
    <li class="breadcrumb-item active">Registrar</li>
{% endblock miga_pan %}

{% block titulo_panel %}
    Formulario de creación del trabajador
{% endblock titulo_panel %}

{% block contenido_panel %}
    <form class="bloquear-ui-enviar" method="post" enctype="multipart/form-data">{% csrf_token %}
        <div class="row">
            <div class="col-12">
                <h4 class="titulo">Información básica del programador</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-6">
                {% bootstrap_field form.tipo_documento %}
            </div>
            <div class="col-xl-6">
                {% bootstrap_field form.numero_documento %}
            </div>
            <div class="col-xl-6">
                {% bootstrap_field form.first_name %}
            </div>
            <div class="col-xl-6">
                {% bootstrap_field form.last_name %}
            </div>
            <div class="col-xl-4 col-sm-12">
                {% bootstrap_field form.email %}
            </div>
            <div class="col-xl-4 col-md-6">
                {% bootstrap_field form.phone_number %}
            </div>
            <div class="col-xl-4 col-md-6">
                {% bootstrap_field form.cargos %}
            </div>
        </div>
        <div class="mt-3">
            {% url 'usuarios:listado_trabajadores' as url_volver%}
            <hr>
            {% include 'componentes/botones/footer_botones.html' with  texto_volver="Volver" texto_accion="Registrar" url_volver=url_volver boton_volver=True boton_accion=True%}
        </div>
       
    </form>
{% endblock contenido_panel %}